// site/src/examples/js/vue_component_display_code.vue
<script setup>
  import IntlTelInput from "intl-tel-input/vue";
  import "intl-tel-input/styles";

  const isValid = ref(null);
  const number = ref(null);
  const errorCode = ref(null);
  const notice = ref(null);

  const handleSubmit = () => {
    if (isValid.value) {
      notice.value = `Valid number: ${number.value}`;
    } else {
      const errorMessage = errorMap[errorCode.value];
      notice.value = `Error: ${errorMessage}`;
    }
  };
</script>

<template>
  <form @submit.prevent="handleSubmit">
    <IntlTelInput
      @changeNumber="number = $event"
      @changeValidity="isValid = $event"
      @changeErrorCode="errorCode = $event"
      :options="{
        initialCountry: 'us',
        loadUtils: () => import('intl-tel-input/utils'),
      }"
    />
    <button class="button" type="submit">Validate</button>
    <div v-if="notice" class="notice">{{ notice }}</div>
  </form>
</template>

// site/src/examples/js/angular_component_display_code.ts
import { Component } from "@angular/core";
import {
  IntlTelInputComponent,
  PHONE_ERROR_MESSAGES,
} from "intl-tel-input/angular";

@Component({
  selector: "app-root",
  template: `
    <form (submit)="handleSubmit($event)">
      <intl-tel-input
        (numberChange)="handleNumberChange($event)"
        (validityChange)="handleValidityChange($event)"
        (errorCodeChange)="handleErrorCodeChange($event)"
        [initOptions]="initOptions"
      />
      <button class="button" type="submit">Validate</button>
      @if (notice) {
        <div class="notice">{{ notice }}</div>
      }
    </form>
  `,
  standalone: true,
  imports: [IntlTelInputComponent],
})
export class AppComponent {
  initOptions = {
    initialCountry: "us",
    loadUtils: () => import("intl-tel-input/utils"),
  };

  isValid: boolean | null = null;
  number: string | null = null;
  errorCode: number | null = null;
  notice: string | null = null;

  handleNumberChange(value: string): void {
    this.number = value;
  }

  handleValidityChange(value: boolean): void {
    this.isValid = value;
  }

  handleErrorCodeChange(value: number | null): void {
    this.errorCode = value;
  }

  handleSubmit(event?: SubmitEvent): void {
    event?.preventDefault();
    if (this.isValid) {
      this.notice = `Valid number: ${this.number}`;
    } else {
      const errorMessage = PHONE_ERROR_MESSAGES[this.errorCode || 0];
      this.notice = `Error: ${errorMessage}`;
    }
  }
}
