// site/src/examples/js/angular_component_display_code.js
import { Component, ViewChild } from "@angular/core";
import { FormControl, FormGroup, ReactiveFormsModule } from "@angular/forms";
import IntlTelInput, { intlTelInput } from "intl-tel-input/angular";
import "intl-tel-input/styles";

const getErrorMessage = (number, errorCode) => {
  if (!number) return "Please enter a number";
  const genericError = "Invalid number";
  const { validationError } = intlTelInput.utils;
  const errorMap = {
    [validationError.INVALID_COUNTRY_CODE]: "Invalid country code",
    [validationError.TOO_SHORT]: "Too short",
    [validationError.TOO_LONG]: "Too long",
    [validationError.INVALID_LENGTH]: genericError,
  };
  return errorMap[errorCode] || genericError;
};

@Component({
  selector: "#app",
  template: `
    <form [formGroup]="fg" (ngSubmit)="handleSubmit()">
      <intl-tel-input
        #telInput
        formControlName="phone"
        (numberChange)="number = $event"
        (validityChange)="isValid = $event"
        (errorCodeChange)="errorCode = $event"
        initialCountry="us"
        [loadUtils]="loadUtils"
      />
      <button type="submit">Submit</button>
      @if (invalidMsg) {
        <div class="invalid-feedback d-block">{{ invalidMsg }}</div>
      }
    </form>
  `,
  standalone: true,
  imports: [IntlTelInput, ReactiveFormsModule],
})
export class AppComponent {
  @ViewChild("telInput") telInput;

  number = "";
  isValid = false;
  errorCode = null;
  showValidation = false;

  loadUtils = () => import("intl-tel-input/utils");

  fg = new FormGroup({
    phone: new FormControl(""),
  });

  get invalidMsg() {
    if (!this.showValidation || this.isValid) return null;
    return getErrorMessage(this.number, this.errorCode);
  }

  handleSubmit() {
    this.showValidation = true;
  }
}

// site/src/examples/js/svelte_component_display_code.svelte
<script>
  import IntlTelInput, { intlTelInput } from "intl-tel-input/svelteWithUtils";
  import "intl-tel-input/styles";

  const getErrorMessage = (number, errorCode) => {
    if (!number) return "Please enter a number";
    const genericError = "Invalid number";
    const { validationError } = intlTelInput.utils;
    const errorMap = {
      [validationError.INVALID_COUNTRY_CODE]: "Invalid country code",
      [validationError.TOO_SHORT]: "Too short",
      [validationError.TOO_LONG]: "Too long",
      [validationError.INVALID_LENGTH]: genericError,
    };
    return errorMap[errorCode] || genericError;
  };

  let number = $state("");
  let isValid = $state(false);
  let errorCode = $state(null);
  let showValidation = $state(false);

  const invalidMsg = $derived.by(() => {
    if (!showValidation || isValid) return null;
    return getErrorMessage(number, errorCode);
  });

  const handleSubmit = (event) => {
    event.preventDefault();
    showValidation = true;
  };
</script>

<form onsubmit={handleSubmit}>
  <IntlTelInput
    onChangeNumber={(n) => (number = n)}
    onChangeValidity={(v) => (isValid = v)}
    onChangeErrorCode={(e) => (errorCode = e)}
    initialCountry="us"
    loadUtils={() => import("intl-tel-input/utils")}
    inputProps={{
      onblur: () => (showValidation = true),
    }}
  />
  <button type="submit">Submit</button>
  {#if invalidMsg}
    <div class="invalid">{invalidMsg}</div>
  {/if}
</form>
