// vue/demo/set-number/App.vue
<script setup>
import { ref } from "vue";
import IntlTelInput from "../../src/intl-tel-input/IntlTelInputWithUtils.vue";

const errorMap = [
  "Invalid number",
  "Invalid country code",
  "Too short",
  "Too long",
  "Invalid number",
];

const isValid = ref(null);
const number = ref(null);
const errorCode = ref(null);
const notice = ref(null);

const intlTelInputRef = ref(null);

const handleSetNumber = () => {
  intlTelInputRef.value?.instance?.setNumber("+14155552671");
};

const handleSubmit = () => {
  if (isValid.value) {
    notice.value = `Valid number: ${number.value}`;
  } else {
    const errorMessage = errorMap[errorCode.value || 0] || "Invalid number";
    notice.value = `Error: ${errorMessage}`;
  }
};
</script>

<template>
  <form>
    <IntlTelInput
      ref="intlTelInputRef"
      @changeNumber="number = $event"
      @changeValidity="isValid = $event"
      @changeErrorCode="errorCode = $event"
      :options="{
        initialCountry: 'us',
      }"
    />
    <button class="button" type="button" @click="handleSetNumber">
      Set Number
    </button>
    <button class="button" type="button" @click="handleSubmit">Validate</button>
    <div v-if="notice" class="notice">{{ notice }}</div>
  </form>
</template>

// svelte/demo/set-number/App.svelte
<script>
  import IntlTelInput from "../../src/intl-tel-input/IntlTelInputWithUtils.svelte";

  const errorMap = [
    "Invalid number",
    "Invalid country code",
    "Too short",
    "Too long",
    "Invalid number",
  ];

  let isValid = $state(null);
  let number = $state(null);
  let errorCode = $state(null);
  let notice = $state(null);

  let intlTelInputRef = $state();

  const handleSetNumber = () => {
    intlTelInputRef?.getInstance()?.setNumber("+14155552671");
  };

  const handleSubmit = () => {
    if (isValid) {
      notice = `Valid number: ${number}`;
    } else {
      const errorMessage = errorMap[errorCode || 0] || "Invalid number";
      notice = `Error: ${errorMessage}`;
    }
  };
</script>

<form>
  <IntlTelInput
    bind:this={intlTelInputRef}
    onChangeNumber={(n) => number = n}
    onChangeValidity={(v) => isValid = v}
    onChangeErrorCode={(e) => errorCode = e}
    options={{ initialCountry: 'us' }}
  />
  <button class="button" type="button" onclick={handleSetNumber}>
    Set Number
  </button>
  <button class="button" type="button" onclick={handleSubmit}>Validate</button>
  {#if notice}
    <div class="notice">{notice}</div>
  {/if}
</form>
