// svelte/src/IntlTelInput.svelte
<script module lang="ts">
  import intlTelInput, { type Iti } from "intl-tel-input";
  export { intlTelInput };
</script>

<script lang="ts">
  import type { SomeOptions } from "intl-tel-input";
  import { onMount, onDestroy } from "svelte";

  type Props = SomeOptions & {
    disabled?: boolean;
    readonly?: boolean;
    inputProps?: Record<string, unknown>;
    initialValue?: string;
    usePreciseValidation?: boolean;
    onChangeNumber?: (number: string) => void;
    onChangeCountry?: (country: string) => void;
    onChangeValidity?: (valid: boolean) => void;
    onChangeErrorCode?: (errorCode: number | null) => void;
  };

  // Props
  let {
    disabled = false,
    readonly = false,
    inputProps = {},
    usePreciseValidation = false,
    initialValue = "",
    onChangeNumber,
    onChangeCountry,
    onChangeValidity,
    onChangeErrorCode,
    ...initOptions
  } = $props() as Props;

  // State
  let inputElement: HTMLInputElement | undefined = $state();
  let instance: Iti | undefined = $state();
  let lastEmittedNumber: string | undefined = $state();
  let lastEmittedCountry: string | undefined = $state();
  let lastEmittedValidity: boolean | undefined = $state();
  let lastEmittedErrorCode: number | null | undefined = $state();
  let hasInitialized = $state(false);

  // Validation helper
  const isValid = (): boolean | null => {
    if (!instance) return null;
    return usePreciseValidation
      ? instance.isValidNumberPrecise()
      : instance.isValidNumber();
  };

  // Update handlers
  const updateValidity = () => {
    if (!instance) return;
    const isCurrentlyValid = isValid();
    if (isCurrentlyValid === null) return;

    const valid = !!isCurrentlyValid;
    const errorCode = valid ? null : instance.getValidationError();

    if (valid !== lastEmittedValidity) {
      lastEmittedValidity = valid;
      onChangeValidity?.(valid);
    }

    if (errorCode !== lastEmittedErrorCode) {
      lastEmittedErrorCode = errorCode;
      onChangeErrorCode?.(errorCode);
    }
  };

  const updateValue = () => {
    if (!instance?.isActive()) {
      return;
    }
    const number = instance.getNumber() ?? "";
    if (number !== lastEmittedNumber) {
      lastEmittedNumber = number;
      onChangeNumber?.(number);
    }
    updateValidity();
  };

  const updateCountry = () => {
    if (!instance?.isActive()) {
      return;
    }
    const country = instance.getSelectedCountryData().iso2 ?? "";
    if (country !== lastEmittedCountry) {
      lastEmittedCountry = country;
      onChangeCountry?.(country);
    }
    updateValue();
  };

  // Lifecycle
  onMount(() => {
    if (inputElement) {
      instance = intlTelInput(inputElement, initOptions as SomeOptions);
      inputElement.addEventListener("countrychange", updateCountry);
      if (initialValue) instance.setNumber(initialValue);
      if (disabled) instance.setDisabled(disabled);
      if (readonly) instance.setReadonly(readonly);

      lastEmittedNumber = instance.getNumber() ?? "";
      lastEmittedCountry = instance.getSelectedCountryData().iso2 ?? "";

      const initialValid = isValid();
      if (initialValid !== null) {
        lastEmittedValidity = !!initialValid;
        lastEmittedErrorCode = initialValid ? null : instance.getValidationError();
      }
      hasInitialized = true;

      // when plugin initialisation has finished (e.g. loaded utils script), update all the state values (updateCountry calls updateValue which calls updateValidity)
      instance.promise.then(updateCountry);
    }
  });

  onDestroy(() => {
    if (inputElement) {
      inputElement.removeEventListener("countrychange", updateCountry);
    }
    instance?.destroy();
  });

  // Watch disabled prop changes (only after initialization)
  $effect(() => {
    if (hasInitialized && instance) {
      instance.setDisabled(disabled);
    }
  });

  // Watch readonly prop changes (only after initialization)
  $effect(() => {
    if (hasInitialized && instance) {
      instance.setReadonly(readonly);
    }
  });

  // Expose instance and input for parent access
  export function getInstance(): Iti | undefined {
    return instance;
  }
  export function getInput(): HTMLInputElement | undefined {
    return inputElement;
  }

  const warnInputProp = (prop: string): void => {
    console.warn(`intl-tel-input: ignoring inputProps.${prop} - see docs for more info.`);
  };

  const sanitizeInputProps = (props: Record<string, unknown>) => {
    // ignore keys that would break functionality
    const {
      type: _type,
      value: _value,
      disabled: _disabled,
      readonly: _readonly,
      oninput: _oninput,
      ...rest
    } = props as Record<string, unknown>;

    if (_type !== undefined) warnInputProp("type");
    if (_value !== undefined) warnInputProp("value");
    if (_disabled !== undefined) warnInputProp("disabled");
    if (_readonly !== undefined) warnInputProp("readonly");
    if (_oninput !== undefined) warnInputProp("oninput");

    return rest;
  };
</script>

<!-- inputProps must come first, so cannot override the other required props -->
<input
  {...sanitizeInputProps(inputProps)}
  bind:this={inputElement}
  type="tel"
  oninput={updateValue}
/>

// react/src/IntlTelInput.tsx
import intlTelInput, { Iti } from "intl-tel-input";
import type { SomeOptions } from "intl-tel-input";
import React, {
  useRef,
  useEffect,
  forwardRef,
  useImperativeHandle,
  useCallback,
} from "react";

// make this available as a named export, so react users can access globals like intlTelInput.utils
export { intlTelInput };

const warnInputProp = (prop: string): void => {
  console.warn(`intl-tel-input: ignoring inputProps.${prop} - see docs for more info.`);
};

type InputProps = Omit<React.ComponentPropsWithoutRef<"input">, "onInput">;

const noop = () => {};

type ItiProps = SomeOptions & {
  initialValue?: string;
  onChangeNumber?: (number: string) => void;
  onChangeCountry?: (country: string) => void;
  onChangeValidity?: (valid: boolean) => void;
  onChangeErrorCode?: (errorCode: number | null) => void;
  usePreciseValidation?: boolean;
  inputProps?: InputProps;
  disabled?: boolean | undefined;
  readOnly?: boolean | undefined;
};

export type IntlTelInputRef = {
  getInstance: () => Iti | null;
  getInput: () => HTMLInputElement | null;
};

// Note: React v19 supports ref forwarding with function components, but we still need to use forwardRef to support React v18
const IntlTelInput = forwardRef(function IntlTelInput(
  {
    initialValue = "",
    onChangeNumber = noop,
    onChangeCountry = noop,
    onChangeValidity = noop,
    onChangeErrorCode = noop,
    usePreciseValidation = false,
    inputProps = {},
    disabled = undefined,
    readOnly = undefined,
    ...initOptions
  }: ItiProps,
  ref: React.ForwardedRef<IntlTelInputRef>,
) {
  const inputRef = useRef<HTMLInputElement | null>(null);
  const itiRef = useRef<Iti | null>(null);
  const lastEmittedNumberRef = useRef<string>();
  const lastEmittedCountryRef = useRef<string>();
  const lastEmittedValidityRef = useRef<boolean>();
  const lastEmittedErrorCodeRef = useRef<number | null>();

  // expose the instance and input ref to the parent component
  useImperativeHandle(ref, () => ({
    getInstance: () => itiRef.current,
    getInput: () => inputRef.current,
  }));

  const update = useCallback((): void => {
    // if the instance is not valid (e.g. has been destroyed/unmounted), do not attempt to call any methods on it
    if (!itiRef.current?.isActive()) {
      return;
    }
    const num = itiRef.current.getNumber() || "";
    const countryIso = itiRef.current.getSelectedCountryData().iso2 || "";
    // note: this number will be in standard E164 format, but any container component can use
    // intlTelInput.utils.formatNumber() to convert this to another format
    // as well as intlTelInput.utils.getNumberType() etc. if need be
    if (num !== lastEmittedNumberRef.current) {
      lastEmittedNumberRef.current = num;
      onChangeNumber(num);
    }
    if (countryIso !== lastEmittedCountryRef.current) {
      lastEmittedCountryRef.current = countryIso;
      onChangeCountry(countryIso);
    }

    const isValid = usePreciseValidation
      ? itiRef.current.isValidNumberPrecise()
      : itiRef.current.isValidNumber();
    const errorCode = isValid ? null : itiRef.current.getValidationError();

    if (isValid !== lastEmittedValidityRef.current) {
      lastEmittedValidityRef.current = isValid;
      onChangeValidity(isValid);
    }
    if (errorCode !== lastEmittedErrorCodeRef.current) {
      lastEmittedErrorCodeRef.current = errorCode;
      onChangeErrorCode(errorCode);
    }
  }, [
    onChangeCountry,
    onChangeErrorCode,
    onChangeNumber,
    onChangeValidity,
    usePreciseValidation,
  ]);

  useEffect(() => {
    if (inputRef.current) {
      itiRef.current = intlTelInput(inputRef.current, initOptions as SomeOptions);
    }
    return (): void => {
      itiRef.current?.destroy();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    // store a reference to the current input ref, which otherwise is already lost in the cleanup function
    const inputRefCurrent = inputRef.current;
    if (inputRefCurrent) {
      inputRefCurrent.addEventListener("countrychange", update);
      // when plugin initialisation has finished (e.g. loaded utils script), update all the state values
      itiRef.current.promise.then(update);
    }
    return (): void => {
      if (inputRefCurrent) {
        inputRefCurrent.removeEventListener("countrychange", update);
      }
    };
  }, [update]);

  useEffect(() => {
    if (itiRef.current && disabled !== undefined) {
      itiRef.current.setDisabled(disabled);
    }
  }, [disabled]);

  useEffect(() => {
    if (itiRef.current && readOnly !== undefined) {
      itiRef.current.setReadonly(readOnly);
    }
  }, [readOnly]);

  // ignore keys that would break functionality
  const {
    type: _type,
    ref: _ref,
    value: _value,
    defaultValue: _defaultValue,
    disabled: _disabled,
    readOnly: _readOnly,
    onInput: _onInput,
    ...sanitizedInputProps
  } = inputProps as unknown as Record<string, unknown>;
  if (_type !== undefined) warnInputProp("type");
  if (_ref !== undefined) warnInputProp("ref");
  if (_value !== undefined) warnInputProp("value");
  if (_defaultValue !== undefined) warnInputProp("defaultValue");
  if (_disabled !== undefined) warnInputProp("disabled");
  if (_readOnly !== undefined) warnInputProp("readOnly");
  if (_onInput !== undefined) warnInputProp("onInput");

  return (
    <input
      {...(sanitizedInputProps as InputProps)}
      type="tel"
      ref={inputRef}
      onInput={update}
      defaultValue={initialValue}
    />
  );
});

export default IntlTelInput;
