// svelte/src/intl-tel-input/IntlTelInput.svelte
<script lang="ts">
  import intlTelInput from "../intl-tel-input";
  import type { Iti } from "../intl-tel-input";
  import type { SomeOptions } from "../modules/types/public-api";
  import { onMount, onDestroy } from "svelte";

  // Props
  let {
    disabled = false,
    inputProps = {},
    options = {},
    usePreciseValidation = false,
    value = "",
    onChangeNumber,
    onChangeCountry,
    onChangeValidity,
    onChangeErrorCode,
  }: {
    disabled?: boolean;
    inputProps?: Record<string, unknown>;
    options?: SomeOptions;
    value?: string;
    usePreciseValidation?: boolean;
    onChangeNumber?: (number: string) => void;
    onChangeCountry?: (country: string) => void;
    onChangeValidity?: (valid: boolean) => void;
    onChangeErrorCode?: (errorCode: number | null) => void;
  } = $props();

  // State
  let inputElement: HTMLInputElement | undefined = $state();
  let instance: Iti | undefined = $state();
  let wasPreviouslyValid: boolean | null = $state(null);
  let hasInitialized = $state(false);

  // Validation helper
  const isValid = (): boolean | null => {
    if (!instance) return null;
    return usePreciseValidation
      ? instance.isValidNumberPrecise()
      : instance.isValidNumber();
  };

  // Update handlers
  const updateValidity = () => {
    const isCurrentlyValid = isValid();
    if (wasPreviouslyValid !== isCurrentlyValid) {
      wasPreviouslyValid = isCurrentlyValid;
      onChangeValidity?.(!!isCurrentlyValid);
      onChangeErrorCode?.(isCurrentlyValid ? null : instance!.getValidationError());
    }
  };

  const updateValue = () => {
    onChangeNumber?.(instance?.getNumber() ?? "");
    updateValidity();
  };

  const updateCountry = () => {
    onChangeCountry?.(instance?.getSelectedCountryData().iso2 ?? "");
    updateValue();
  };

  // Lifecycle
  onMount(() => {
    if (inputElement) {
      instance = intlTelInput(inputElement, options);
      inputElement.addEventListener("countrychange", updateCountry);
      if (value) instance.setNumber(value);
      if (disabled) instance.setDisabled(disabled);
      wasPreviouslyValid = isValid();
      hasInitialized = true;
    }
  });

  onDestroy(() => {
    if (inputElement) {
      inputElement.removeEventListener("countrychange", updateCountry);
    }
    instance?.destroy();
  });

  // Watch disabled prop changes (only after initialization)
  $effect(() => {
    if (hasInitialized && instance) {
      instance.setDisabled(disabled);
    }
  });

  // Expose instance and input for parent access
  export function getInstance(): Iti | undefined {
    return instance;
  }
  export function getInput(): HTMLInputElement | undefined {
    return inputElement;
  }
</script>

<input
  bind:this={inputElement}
  type="tel"
  oninput={updateValue}
  {...inputProps}
/>

// vue/src/intl-tel-input/IntlTelInput.vue
<script setup>
import intlTelInput from "../intl-tel-input";
import { onMounted, onUnmounted, ref, watch } from "vue";

const model = defineModel({
  type: String,
  default: "",
});

const props = defineProps({
  disabled: {
    type: Boolean,
    default: false,
  },

  inputProps: {
    type: Object,
    default: () => ({}),
  },

  options: {
    type: Object,
    default: () => ({}),
  },

  value: {
    type: String,
    default: "",
  },
});

const emit = defineEmits([
  "changeNumber",
  "changeCountry",
  "changeValidity",
  "changeErrorCode",
]);

const input = ref();
const instance = ref();
const wasPreviouslyValid = ref(false);

const isValid = () => {
  if (instance.value) {
    return props.options.strictMode
      ? instance.value.isValidNumberPrecise()
      : instance.value.isValidNumber();
  }

  return null;
};

const updateValidity = () => {
  let isCurrentlyValid = isValid();

  if (wasPreviouslyValid.value !== isCurrentlyValid) {
    wasPreviouslyValid.value = isCurrentlyValid;

    emit("changeValidity", !!isCurrentlyValid);
    emit(
      "changeErrorCode",
      isCurrentlyValid ? null : instance.value.getValidationError()
    );
  }
};

const updateValue = () => {
  emit("changeNumber", instance.value?.getNumber() ?? "");
  updateValidity();
};

const updateCountry = () => {
  emit("changeCountry", instance.value?.getSelectedCountryData().iso2 ?? "");
  updateValue();
  updateValidity();
};

onMounted(() => {
  if (input.value) {
    instance.value = intlTelInput(input.value, props.options);

    if (props.value) {
      instance.value.setNumber(props.value);
    }

    if (props.disabled) {
      instance.value.setDisabled(props.disabled);
    }
  }
});

watch(
  () => props.disabled,
  (newValue) => instance.value?.setDisabled(newValue)
);

onUnmounted(() => instance.value?.destroy());

defineExpose({ instance, input });
</script>

<template>
  <input
    ref="input"
    v-model="model"
    type="tel"
    @countrychange="updateCountry"
    @input="updateValue"
    v-bind="inputProps"
  />
</template>
