// packages/svelte/demo/set-country/App.svelte
<script>
  import IntlTelInput from "../../src/IntlTelInputWithUtils.svelte";

  let country = $state("us");
  let intlTelInputRef = $state();

  const handleSetCountry = () => {
    intlTelInputRef?.getInstance()?.setCountry("gb");
  };
</script>

<form>
  <div class="d-flex align-items-start gap-2">
    <IntlTelInput
      bind:this={intlTelInputRef}
      onChangeCountry={(c) => country = c}
      initialCountry="us"
      inputProps={{ class: "form-control" }}
      searchInputClass="form-control"
    />
    <button class="btn btn-primary" type="button" onclick={handleSetCountry}>
      Set Country to GB
    </button>
  </div>
  <p>Current country (per parent state): {country}</p>
</form>

// packages/vue/demo/set-country/App.vue
<script setup>
import { ref } from "vue";
import IntlTelInput from "../../src/indexWithUtils";

const country = ref("us");
const intlTelInputRef = ref(null);

const handleSetCountry = () => {
  intlTelInputRef.value?.instance?.setCountry("gb");
};
</script>

<template>
  <form>
    <div class="d-flex align-items-start gap-2">
      <IntlTelInput
        ref="intlTelInputRef"
        @changeCountry="country = $event"
        initialCountry="us"
        :input-props="{ class: 'form-control' }"
        search-input-class="form-control"
      />
      <button class="btn btn-primary" type="button" @click="handleSetCountry">
        Set Country to GB
      </button>
    </div>
    <p>Current country (per parent state): {{ country }}</p>
  </form>
</template>
