// packages/svelte/demo/toggle-disabled/App.svelte
<script>
  import IntlTelInput from "../../src/IntlTelInputWithUtils.svelte";

  let isDisabled = $state(true);

  const toggleDisabled = () => {
    isDisabled = !isDisabled;
  };
</script>

<form>
  <div class="d-flex align-items-start gap-2">
    <IntlTelInput
      disabled={isDisabled}
      inputProps={{ class: "form-control" }}
      searchInputClass="form-control"
    />
    <button class="btn btn-primary" type="button" onclick={toggleDisabled}>Toggle</button>
  </div>
</form>

// packages/vue/demo/toggle-disabled/App.vue
<script setup>
import { ref } from "vue";
import IntlTelInput from "../../src/indexWithUtils";

const isDisabled = ref(true);

const toggleDisabled = () => {
  isDisabled.value = !isDisabled.value;
};
</script>

<template>
  <form>
    <div class="d-flex align-items-start gap-2">
      <IntlTelInput
        :disabled="isDisabled"
        :input-props="{ class: 'form-control' }"
        search-input-class="form-control"
      />
      <button class="btn btn-primary" type="button" @click="toggleDisabled">Toggle</button>
    </div>
  </form>
</template>
