// packages/vue/src/IntlTelInput.vue
<script setup lang="ts">
import intlTelInput, { type SomeOptions, type ValidationError } from "intl-tel-input";
import {
  onMounted,
  onUnmounted,
  ref,
  shallowRef,
  watch,
  computed,
  getCurrentInstance,
} from "vue";
import type { Props } from "./props";

const props = withDefaults(defineProps<Props & SomeOptions>(), {
  disabled: false,
  readonly: false,
  usePreciseValidation: false,
  inputProps: () => ({}),
});

defineOptions({ inheritAttrs: false });

type StrictRejectSource = "key" | "paste";
type StrictRejectReason = "invalid" | "max-length";
type StrictRejectDetail = {
  source: StrictRejectSource;
  rejectedInput: string;
  reason: StrictRejectReason;
};

const emit = defineEmits<{
  (e: "changeNumber", value: string): void;
  (e: "changeCountry", value: string): void;
  (e: "changeValidity", value: boolean): void;
  (e: "changeErrorCode", value: ValidationError | null): void;
  (e: "openCountrySelector"): void;
  (e: "closeCountrySelector"): void;
  (e: "strictReject", source: StrictRejectSource, rejectedInput: string, reason: StrictRejectReason): void;
  (e: "update:modelValue", value: string): void;
}>();

const warnInputProp = (prop: string): void => {
  console.warn(`intl-tel-input: ignoring inputProps.${prop} - see docs for more info.`);
};

const ignoredInputProps = new Set(["type", "value", "disabled", "readonly", "onInput", "oninput"]);

// Classes the library adds directly to the input (e.g. iti__tel-input)
const libraryInputClasses = ref("");

const sanitizedInputProps = computed(() => {
  const input = (props.inputProps ?? {}) as Record<string, unknown>;
  const rest: Record<string, unknown> = {};
  for (const [key, val] of Object.entries(input)) {
    if (ignoredInputProps.has(key)) {
      warnInputProp(key);
    } else if (key === "class") {
      // Re-apply the library's own classes alongside the consumer's, as Vue owns the attribute
      // (filter out empties so we never emit a stray "undefined" class or leading whitespace)
      rest[key] = [libraryInputClasses.value, val].filter(Boolean).join(" ");
    } else {
      rest[key] = val;
    }
  }
  return rest;
});

const displayed = computed(
  () =>
    props.modelValue ??
    props.initialValue ??
    "",
);

const vm = getCurrentInstance();

const libraryOptionKeys = Object.keys(intlTelInput.defaults);

// Vue will coerce absent Boolean props to `false` when props are declared at runtime.
// That can accidentally override the library's own defaults.
//
// To preserve library defaults, only pass through keys that:
// 1) are real library option keys, and
// 2) were actually provided by the parent
//
// We normalize raw vnode prop keys to camelCase before checking, because Vue's
// template compiler may pass props in kebab-case depending on how the consumer
// writes the attribute.
const initOptions = computed<SomeOptions>(() => {
  const rawPassedProps = (vm?.vnode.props ?? {}) as Record<string, unknown>;
  const passedCamelKeys = new Set(
    Object.keys(rawPassedProps).map((k) => k.replace(/-([a-z])/g, (_, c) => c.toUpperCase())),
  );

  const cleanedOptions: Record<string, unknown> = {};
  libraryOptionKeys.forEach((optionKey) => {
    if (!passedCamelKeys.has(optionKey)) {
      return;
    }
    const value = (props as Record<string, unknown>)[optionKey];
    if (value !== undefined) cleanedOptions[optionKey] = value;
  });

  return cleanedOptions as SomeOptions;
});

const input = ref<HTMLInputElement | null>(null);
// Use shallowRef so Vue does not Proxy-wrap the Iti class instance.
// A reactive Proxy breaks private fields (e.g. `#ui`) when calling instance methods.
const instance = shallowRef<ReturnType<typeof intlTelInput> | null>(null);
const lastEmittedNumber = ref<string>();
const lastEmittedCountry = ref<string>();
const lastEmittedValidity = ref<boolean>();
const lastEmittedErrorCode = ref<ValidationError | null>();
// if an input event fires before utils has loaded, we defer the update until the promise resolves
let pendingUpdate = false;

const isValid = () => (props.usePreciseValidation
  ? instance.value!.isValidNumberPrecise()
  : instance.value!.isValidNumber()) ?? false;

const updateValidity = () => {
  if (!instance.value?.isActive()) {
    return;
  }
  // if utils has not loaded yet, isValidNumber/getValidationError will throw. defer until the promise resolves.
  if (!intlTelInput.utils) {
    pendingUpdate = true;
    return;
  }
  const valid = isValid();
  const errorCode = valid
    ? null
    : instance.value!.getValidationError();

  if (valid !== lastEmittedValidity.value) {
    lastEmittedValidity.value = valid;
    emit("changeValidity", valid);
  }

  if (errorCode !== lastEmittedErrorCode.value) {
    lastEmittedErrorCode.value = errorCode;
    emit("changeErrorCode", errorCode);
  }
};

const updateValue = () => {
  if (!instance.value?.isActive()) {
    return;
  }
  // if utils has not loaded yet, getNumber will throw. defer until the promise resolves.
  if (!intlTelInput.utils) {
    pendingUpdate = true;
    return;
  }
  const number = instance.value.getNumber() ?? "";
  if (number !== lastEmittedNumber.value) {
    lastEmittedNumber.value = number;
    emit("changeNumber", number);
    emit("update:modelValue", number);
  }

  updateValidity();
};

const updateCountry = () => {
  if (!instance.value?.isActive()) {
    return;
  }
  const country = instance.value.getSelectedCountry()?.iso2 ?? "";
  if (country !== lastEmittedCountry.value) {
    lastEmittedCountry.value = country;
    emit("changeCountry", country);
  }
  updateValue();
};

const handleOpen = (): void => emit("openCountrySelector");
const handleClose = (): void => emit("closeCountrySelector");
const handleStrictReject = (e: Event): void => {
  const { source, rejectedInput, reason } = (e as CustomEvent<StrictRejectDetail>).detail;
  emit("strictReject", source, rejectedInput, reason);
};

onMounted(() => {
  if (!input.value) {
    return;
  }

  //* Record only the classes the library itself adds during init (iti__tel-input, plus any
  //* classNames.input), by diffing the class list across the call. Capturing the whole className
  //* would also scoop up any inputProps.class already rendered, which would then be re-applied on
  //* every subsequent render - so a changed inputProps.class would leave the old value behind, and
  //* an unchanged one would be duplicated.
  const classesBeforeInit = new Set(input.value.classList);
  instance.value = intlTelInput(input.value, initOptions.value);
  libraryInputClasses.value = Array.from(input.value.classList)
    .filter((className) => !classesBeforeInit.has(className))
    .join(" ");

  //* Attach input listener AFTER intlTelInput() so the core's #handleInputEvent (also added in intlTelInput()) runs first on each native input event. That guarantees getSelectedCountry() / getNumber() return the post-update values inside updateCountry. A template-bound @input would be registered before mount and so would run before the core's listener, reading stale state.
  input.value.addEventListener("input", updateCountry);
  input.value.addEventListener("open:countryselector", handleOpen);
  input.value.addEventListener("close:countryselector", handleClose);
  input.value.addEventListener("strict:reject", handleStrictReject);

  if (props.disabled) {
    instance.value.setDisabled(props.disabled);
  }
  if (props.readonly) {
    instance.value.setReadonly(props.readonly);
  }

  lastEmittedCountry.value = instance.value.getSelectedCountry()?.iso2 ?? "";

  // wait for utils to load before calling methods that require it (getNumber, setNumber, isValidNumber, etc.)
  instance.value.promise.then(() => {
    if (!instance.value?.isActive()) {
      return;
    }
    if (displayed.value) {
      instance.value.setNumber(displayed.value);
    }
    // if an input event fired during the utils-loading gap, replay it now so the skipped emissions fire.
    // otherwise seed silently so we don't fire change callbacks on initial mount.
    if (pendingUpdate) {
      pendingUpdate = false;
      updateCountry();
    } else {
      lastEmittedNumber.value = instance.value.getNumber() ?? "";
      lastEmittedValidity.value = isValid();
      lastEmittedErrorCode.value = lastEmittedValidity.value
        ? null
        : instance.value.getValidationError();
    }
  });
});

watch(
  () => props.disabled,
  (newValue) => instance.value?.setDisabled(newValue),
);

watch(
  () => props.readonly,
  (newValue) => instance.value?.setReadonly(newValue),
);

watch(
  () => displayed.value,
  (val) => {
    if (!instance.value) {
      return;
    }

    // wait for utils to load before calling methods that require it
    instance.value.promise.then(() => {
      if (!instance.value?.isActive()) {
        return;
      }
      // Avoid cursor jumping when typing
      const next = val ?? "";
      const currentCanonical = instance.value.getNumber() ?? "";
      const isFocused = document.activeElement === input.value;

      if (isFocused || currentCanonical === next) {
        return;
      }

      instance.value.setNumber(next);
      updateValidity();
    });
  },
  { flush: "post" },
);

onUnmounted(() => {
  if (input.value) {
    input.value.removeEventListener("input", updateCountry);
    input.value.removeEventListener("open:countryselector", handleOpen);
    input.value.removeEventListener("close:countryselector", handleClose);
    input.value.removeEventListener("strict:reject", handleStrictReject);
  }
  instance.value?.destroy();
});

defineExpose({ instance, input });
</script>

<template>
  <!-- must come first, so cannot override the other required props -->
  <input
    v-bind="sanitizedInputProps"
    ref="input"
    type="tel"
  />
</template>

// packages/svelte/src/IntlTelInput.svelte
<script module lang="ts">
  import intlTelInput, { type Iti } from "intl-tel-input";
  export { intlTelInput };
</script>

<script lang="ts">
  // Resolves to IntlTelInput.svelte.d.ts (the type declaration file for this component).
  import type { Props } from "./IntlTelInput.svelte";
  import type { SomeOptions, ValidationError } from "intl-tel-input";
  import { onMount, onDestroy } from "svelte";

  // Props
  let {
    disabled = false,
    readonly = false,
    inputProps = {},
    usePreciseValidation = false,
    initialValue = "",
    value = undefined,
    onChangeNumber,
    onChangeCountry,
    onChangeValidity,
    onChangeErrorCode,
    onOpenCountrySelector,
    onCloseCountrySelector,
    onStrictReject,
    ...initOptions
  } = $props() as Props;

  type StrictRejectDetail = {
    source: "key" | "paste";
    rejectedInput: string;
    reason: "invalid" | "max-length";
  };

  // State
  let inputElement: HTMLInputElement | undefined = $state();
  let instance: Iti | undefined = $state();
  // Classes the library adds directly to the input (e.g. iti__tel-input)
  let libraryInputClasses = $state("");
  let lastEmittedNumber: string | undefined = $state();
  let lastEmittedCountry: string | undefined = $state();
  let lastEmittedValidity: boolean | undefined = $state();
  let lastEmittedErrorCode: ValidationError | null | undefined = $state();
  let hasInitialized = $state(false);
  // if an input event fires before utils has loaded, we defer the update until the promise resolves
  let pendingUpdate = false;

  // Validation helper
  const isValid = (): boolean | null => {
    if (!instance) return null;
    return usePreciseValidation
      ? instance.isValidNumberPrecise()
      : instance.isValidNumber();
  };

  // Update handlers
  const updateValidity = () => {
    if (!instance) return;
    // if utils has not loaded yet, isValidNumber/getValidationError will throw. defer until the promise resolves.
    if (!intlTelInput.utils) {
      pendingUpdate = true;
      return;
    }
    const isCurrentlyValid = isValid();
    if (isCurrentlyValid === null) return;

    const valid = !!isCurrentlyValid;
    const errorCode = valid ? null : instance.getValidationError();

    if (valid !== lastEmittedValidity) {
      lastEmittedValidity = valid;
      onChangeValidity?.(valid);
    }

    if (errorCode !== lastEmittedErrorCode) {
      lastEmittedErrorCode = errorCode;
      onChangeErrorCode?.(errorCode);
    }
  };

  const updateValue = () => {
    if (!instance?.isActive()) {
      return;
    }
    // if utils has not loaded yet, getNumber will throw. defer until the promise resolves.
    if (!intlTelInput.utils) {
      pendingUpdate = true;
      return;
    }
    const number = instance.getNumber() ?? "";
    if (number !== lastEmittedNumber) {
      lastEmittedNumber = number;
      onChangeNumber?.(number);
    }
    updateValidity();
  };

  const updateCountry = () => {
    if (!instance?.isActive()) {
      return;
    }
    const country = instance.getSelectedCountry()?.iso2 ?? "";
    if (country !== lastEmittedCountry) {
      lastEmittedCountry = country;
      onChangeCountry?.(country);
    }
    updateValue();
  };

  const handleOpenCountrySelector = (): void => onOpenCountrySelector?.();
  const handleCloseCountrySelector = (): void => onCloseCountrySelector?.();
  const handleStrictReject = (e: Event): void => {
    const { source, rejectedInput, reason } = (e as CustomEvent<StrictRejectDetail>).detail;
    onStrictReject?.(source, rejectedInput, reason);
  };

  // Lifecycle
  onMount(() => {
    if (inputElement) {
      //* Record only the classes the library itself adds during init (iti__tel-input, plus any
      //* classNames.input), by diffing the class list across the call. Capturing the whole className
      //* would also scoop up any inputProps.class already rendered, which would then be re-applied on
      //* every subsequent render - so a changed inputProps.class would leave the old value behind,
      //* and an unchanged one would be duplicated.
      const classesBeforeInit = new Set(inputElement.classList);
      instance = intlTelInput(inputElement, initOptions as SomeOptions);
      libraryInputClasses = Array.from(inputElement.classList)
        .filter((className) => !classesBeforeInit.has(className))
        .join(" ");
      if (disabled) instance.setDisabled(disabled);
      if (readonly) instance.setReadonly(readonly);

      inputElement.addEventListener("open:countryselector", handleOpenCountrySelector);
      inputElement.addEventListener("close:countryselector", handleCloseCountrySelector);
      inputElement.addEventListener("strict:reject", handleStrictReject);

      lastEmittedCountry = instance.getSelectedCountry()?.iso2 ?? "";
      hasInitialized = true;

      // wait for utils to load before calling methods that require it (getNumber, setNumber, isValidNumber, etc.)
      instance.promise.then(() => {
        if (!instance?.isActive()) return;
        if (initialValue) instance.setNumber(initialValue);
        // if an input event fired during the utils-loading gap, replay it now so the skipped emissions fire.
        // otherwise seed silently so we don't fire change callbacks on initial mount.
        if (pendingUpdate) {
          pendingUpdate = false;
          updateCountry();
        } else {
          lastEmittedNumber = instance.getNumber() ?? "";
          const initialValid = isValid();
          if (initialValid !== null) {
            lastEmittedValidity = !!initialValid;
            lastEmittedErrorCode = initialValid ? null : instance.getValidationError();
          }
        }
      });
    }
  });

  onDestroy(() => {
    if (inputElement) {
      inputElement.removeEventListener("open:countryselector", handleOpenCountrySelector);
      inputElement.removeEventListener("close:countryselector", handleCloseCountrySelector);
      inputElement.removeEventListener("strict:reject", handleStrictReject);
    }
    instance?.destroy();
  });

  // Watch disabled prop changes (only after initialization)
  $effect(() => {
    if (hasInitialized && instance) {
      instance.setDisabled(disabled);
    }
  });

  // Watch readonly prop changes (only after initialization)
  $effect(() => {
    if (hasInitialized && instance) {
      instance.setReadonly(readonly);
    }
  });

  // Watch value prop changes (only after initialization).
  // If value is undefined, the component is uncontrolled — do not touch the input
  // (otherwise we would clobber any initialValue with an empty string on mount).
  $effect(() => {
    if (!hasInitialized || !instance || value === undefined) {
      return;
    }
    const next = value ?? "";
    // wait for utils to load before calling methods that require it
    instance.promise.then(() => {
      if (!instance?.isActive()) return;
      const currentCanonical = instance.getNumber() ?? "";
      const isFocused = document.activeElement === inputElement;
      if (isFocused || currentCanonical === next) {
        return;
      }
      instance.setNumber(next);
      updateValidity();
    });
  });

  // Expose instance and input for parent access
  export function getInstance(): Iti | undefined {
    return instance;
  }
  export function getInput(): HTMLInputElement | undefined {
    return inputElement;
  }

  const warnInputProp = (prop: string): void => {
    console.warn(`intl-tel-input: ignoring inputProps.${prop} - see docs for more info.`);
  };

  const ignoredInputProps = new Set(["type", "value", "disabled", "readonly", "oninput"]);

  const sanitizeInputProps = (props: Record<string, unknown>) => {
    const rest: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(props)) {
      if (ignoredInputProps.has(key)) {
        warnInputProp(key);
      } else if (key === "class") {
        // Re-apply the library's own classes alongside the consumer's, as Svelte owns the attribute
        // (filter out empties so we never emit a stray "undefined" class or leading whitespace)
        rest[key] = [libraryInputClasses, val].filter(Boolean).join(" ");
      } else {
        rest[key] = val;
      }
    }
    return rest;
  };
</script>

<!-- inputProps must come first, so cannot override the other required props -->
<input
  {...sanitizeInputProps(inputProps)}
  bind:this={inputElement}
  type="tel"
  oninput={updateCountry}
/>
