// svelte/demo/toggle-disabled/App.svelte
<script>
  import IntlTelInput from "../../src/intl-tel-input/IntlTelInputWithUtils.svelte";

  let isDisabled = $state(true);

  const toggleDisabled = () => {
    isDisabled = !isDisabled;
  };
</script>

<form>
  <IntlTelInput disabled={isDisabled} />
  <button class="button" type="button" onclick={toggleDisabled}>Toggle</button>
</form>

// vue/demo/toggle-disabled/App.vue
<script setup>
import { ref } from "vue";
import IntlTelInput from "../../src/intl-tel-input/IntlTelInputWithUtils.vue";

const isDisabled = ref(true);

const toggleDisabled = () => {
  isDisabled.value = !isDisabled.value;
};
</script>

<template>
  <form>
    <IntlTelInput :disabled="isDisabled" />
    <button class="button" type="button" @click="toggleDisabled">Toggle</button>
  </form>
</template>
