// vue/src/IntlTelInput.vue
<script setup lang="ts">
import intlTelInput from "./intl-tel-input";
import type { SomeOptions } from "./modules/types/public-api";
import { onMounted, onUnmounted, ref, shallowRef, watch, computed } from "vue";
import type { InputHTMLAttributes } from "vue";

interface Props {
  options?: SomeOptions;
  usePreciseValidation?: boolean;
  disabled?: boolean;
  readonly?: boolean;
  inputProps?: InputHTMLAttributes;
  value?: string | null;
  modelValue?: string | null;
}

const props = withDefaults(defineProps<Props>(), {
  disabled: false,
  readonly: false,
  usePreciseValidation: false,
  inputProps: () => ({}),
  options: () => ({}),
});

defineOptions({ inheritAttrs: false });

const emit = defineEmits([
  "changeNumber",
  "changeCountry",
  "changeValidity",
  "changeErrorCode",
  "update:modelValue",
]);

const sanitizedInputProps = computed(() => {
  // ignore keys that would break functionality
  const {
    type: _type,
    ref: _ref,
    value: _value,
    // disabled: _disabled,
    onInput: _onInput,
    oninput: _oninput,
    onCountrychange: _onCountrychange,
    onCountryChange: _onCountryChange,
    ...rest
  } = (props.inputProps ?? {}) as Record<string, unknown>;

  return rest;
});

const displayed = computed(() => props.value ?? props.modelValue ?? "");

const input = ref<HTMLInputElement | null>(null);
// Use shallowRef so Vue does not Proxy-wrap the Iti class instance.
// A reactive Proxy breaks private fields (e.g. `#ui`) when calling instance methods.
const instance = shallowRef<ReturnType<typeof intlTelInput> | null>(null);
const lastEmittedNumber = ref<string>();
const lastEmittedCountry = ref<string>();
const lastEmittedValidity = ref<boolean>();
const lastEmittedErrorCode = ref<number | null>();

const isValid = () => props.usePreciseValidation
  ? instance.value!.isValidNumberPrecise()
  : instance.value!.isValidNumber();

const updateValidity = () => {
  const valid = isValid();
  const errorCode = valid
    ? null
    : instance.value!.getValidationError();

  if (valid !== lastEmittedValidity.value) {
    lastEmittedValidity.value = valid;
    emit("changeValidity", valid);
  }

  if (errorCode !== lastEmittedErrorCode.value) {
    lastEmittedErrorCode.value = errorCode;
    emit("changeErrorCode", errorCode);
  }
};

const updateValue = () => {
  if (!instance.value?.isActive()) {
    return;
  }
  const number = instance.value.getNumber() ?? "";
  if (number !== lastEmittedNumber.value) {
    lastEmittedNumber.value = number;
    emit("changeNumber", number);
    emit("update:modelValue", number);
  }

  updateValidity();
};

const updateCountry = () => {
  if (!instance.value?.isActive()) {
    return;
  }
  const country = instance.value.getSelectedCountryData().iso2 ?? "";
  if (country !== lastEmittedCountry.value) {
    lastEmittedCountry.value = country;
    emit("changeCountry", country);
  }
  updateValue();
};

onMounted(() => {
  if (!input.value) {
    return;
  }

  instance.value = intlTelInput(input.value, props.options);

  if (displayed.value) {
    instance.value.setNumber(displayed.value);
  }
  if (props.disabled) {
    instance.value.setDisabled(props.disabled);
  }
  if (props.readonly) {
    instance.value.setReadonly(props.readonly);
  }

  lastEmittedNumber.value = instance.value.getNumber() ?? "";
  lastEmittedCountry.value = instance.value.getSelectedCountryData().iso2 ?? "";

  lastEmittedValidity.value = isValid();
  lastEmittedErrorCode.value = lastEmittedValidity.value
    ? null
    : instance.value.getValidationError();

  // update state values once plugin initialisation has finished (e.g. loaded utils script). note that updateCountry calls updateValue, which calls updateValidity.
  instance.value.promise.then(updateCountry);
});

watch(
  () => props.disabled,
  (newValue) => instance.value?.setDisabled(newValue),
);

watch(
  () => props.readonly,
  (newValue) => instance.value?.setReadonly(newValue),
);

watch(
  () => displayed.value,
  (val) => {
    if (!instance.value) {
      return;
    }

    // Avoid cursor jumping when typing
    const next = val ?? "";
    const currentCanonical = instance.value.getNumber() ?? "";
    const isFocused = document.activeElement === input.value;

    if (isFocused || currentCanonical === next) {
      return;
    }

    instance.value.setNumber(next);
    updateValidity();
  },
  { flush: "post" },
)

onUnmounted(() => instance.value?.destroy());

defineExpose({ instance, input });
</script>

<template>
  <!-- must come first, so cannot override the other required props -->
  <input
    v-bind="sanitizedInputProps"
    ref="input"
    type="tel"
    @countrychange="updateCountry"
    @input="updateValue"
  />
</template>

// svelte/src/intl-tel-input/IntlTelInput.svelte
<script lang="ts">
  import intlTelInput from "../intl-tel-input";
  import type { Iti } from "../intl-tel-input";
  import type { SomeOptions } from "../modules/types/public-api";
  import { onMount, onDestroy } from "svelte";

  // Props
  let {
    disabled = false,
    readonly = false,
    inputProps = {},
    options = {},
    usePreciseValidation = false,
    value = "",
    onChangeNumber,
    onChangeCountry,
    onChangeValidity,
    onChangeErrorCode,
  }: {
    disabled?: boolean;
    readonly?: boolean;
    inputProps?: Record<string, unknown>;
    options?: SomeOptions;
    value?: string;
    usePreciseValidation?: boolean;
    onChangeNumber?: (number: string) => void;
    onChangeCountry?: (country: string) => void;
    onChangeValidity?: (valid: boolean) => void;
    onChangeErrorCode?: (errorCode: number | null) => void;
  } = $props();

  // State
  let inputElement: HTMLInputElement | undefined = $state();
  let instance: Iti | undefined = $state();
  let lastEmittedNumber: string | undefined = $state();
  let lastEmittedCountry: string | undefined = $state();
  let lastEmittedValidity: boolean | undefined = $state();
  let lastEmittedErrorCode: number | null | undefined = $state();
  let hasInitialized = $state(false);

  // Validation helper
  const isValid = (): boolean | null => {
    if (!instance) return null;
    return usePreciseValidation
      ? instance.isValidNumberPrecise()
      : instance.isValidNumber();
  };

  // Update handlers
  const updateValidity = () => {
    if (!instance) return;
    const isCurrentlyValid = isValid();
    if (isCurrentlyValid === null) return;

    const valid = !!isCurrentlyValid;
    const errorCode = valid ? null : instance.getValidationError();

    if (valid !== lastEmittedValidity) {
      lastEmittedValidity = valid;
      onChangeValidity?.(valid);
    }

    if (errorCode !== lastEmittedErrorCode) {
      lastEmittedErrorCode = errorCode;
      onChangeErrorCode?.(errorCode);
    }
  };

  const updateValue = () => {
    if (!instance?.isActive()) {
      return;
    }
    const number = instance.getNumber() ?? "";
    if (number !== lastEmittedNumber) {
      lastEmittedNumber = number;
      onChangeNumber?.(number);
    }
    updateValidity();
  };

  const updateCountry = () => {
    if (!instance?.isActive()) {
      return;
    }
    const country = instance.getSelectedCountryData().iso2 ?? "";
    if (country !== lastEmittedCountry) {
      lastEmittedCountry = country;
      onChangeCountry?.(country);
    }
    updateValue();
  };

  // Lifecycle
  onMount(() => {
    if (inputElement) {
      instance = intlTelInput(inputElement, options);
      inputElement.addEventListener("countrychange", updateCountry);
      if (value) instance.setNumber(value);
      if (disabled) instance.setDisabled(disabled);
      if (readonly) instance.setReadonly(readonly);

      lastEmittedNumber = instance.getNumber() ?? "";
      lastEmittedCountry = instance.getSelectedCountryData().iso2 ?? "";

      const initialValid = isValid();
      if (initialValid !== null) {
        lastEmittedValidity = !!initialValid;
        lastEmittedErrorCode = initialValid ? null : instance.getValidationError();
      }
      hasInitialized = true;

      // when plugin initialisation has finished (e.g. loaded utils script), update all the state values (updateCountry calls updateValue which calls updateValidity)
      instance.promise.then(updateCountry);
    }
  });

  onDestroy(() => {
    if (inputElement) {
      inputElement.removeEventListener("countrychange", updateCountry);
    }
    instance?.destroy();
  });

  // Watch disabled prop changes (only after initialization)
  $effect(() => {
    if (hasInitialized && instance) {
      instance.setDisabled(disabled);
    }
  });

  // Watch readonly prop changes (only after initialization)
  $effect(() => {
    if (hasInitialized && instance) {
      instance.setReadonly(readonly);
    }
  });

  // Expose instance and input for parent access
  export function getInstance(): Iti | undefined {
    return instance;
  }
  export function getInput(): HTMLInputElement | undefined {
    return inputElement;
  }

  const sanitizeInputProps = (props: Record<string, unknown>) => {
    // ignore keys that would break functionality
    const {
      value: _value,
      // disabled: _disabled,
      ...rest
    } = props as Record<string, unknown>;

    return rest;
  };
</script>

<!-- inputProps must come first, so cannot override the other required props -->
<input
  {...sanitizeInputProps(inputProps)}
  bind:this={inputElement}
  type="tel"
  oninput={updateValue}
/>
