// site/src/examples/svelte-component/display-existing-number/display_code.svelte
<script>
  import IntlTelInput from "intl-tel-input/svelte";
  import "intl-tel-input/styles";
</script>

<label for="phone">Phone number</label>
<IntlTelInput
  separateDialCode={true}
  initialValue="+447733312345"
  loadUtils={() => import("intl-tel-input/utils")}
  inputProps={{ id: "phone" }}
/>

// site/src/examples/angular-component/display-existing-number/display_code.js
import { Component } from "@angular/core";
import IntlTelInput from "intl-tel-input/angular";
import "intl-tel-input/styles";

@Component({
  selector: "#app",
  template: `
    <label for="phone">Phone number</label>
    <intl-tel-input
      initialValue="+447733312345"
      [inputAttributes]="{ id: 'phone' }"
      [separateDialCode]="true"
      [loadUtils]="loadUtils"
    />
  `,
  standalone: true,
  imports: [IntlTelInput],
})
export class AppComponent {
  loadUtils = () => import("intl-tel-input/utils");
}
