// vue/demo/validation/App.vue
<script setup>
import { ref } from "vue";
import IntlTelInput, { intlTelInput } from "../../src/exports/IntlTelInputWithUtils";

const getErrorMessage = (errorCode) => {
  const genericError = "Invalid number";
  const { validationError } = intlTelInput.utils;
  const errorMap = {
    [validationError.INVALID_COUNTRY_CODE]: "Invalid country code",
    [validationError.TOO_SHORT]: "Too short",
    [validationError.TOO_LONG]: "Too long",
    [validationError.INVALID_LENGTH]: genericError,
  };
  return errorMap[errorCode] || genericError;
};

const isValid = ref(null);
const number = ref(null);
const errorCode = ref(null);
const notice = ref(null);

const handleSubmit = () => {
  if (isValid.value) {
    notice.value = `Valid number: ${number.value}`;
  } else {
    const errorMessage = getErrorMessage(errorCode.value);
    notice.value = `Error: ${errorMessage}`;
  }
};
</script>

<template>
  <form>
    <IntlTelInput
      @changeNumber="number = $event"
      @changeValidity="isValid = $event"
      @changeErrorCode="errorCode = $event"
      initialCountry="us"
    />
    <button class="button" type="button" @click="handleSubmit">Validate</button>
    <div v-if="notice" class="notice">{{ notice }}</div>
  </form>
</template>

// svelte/demo/validation/App.svelte
<script>
  import IntlTelInput, { intlTelInput } from "../../src/IntlTelInputWithUtils.svelte";

  const getErrorMessage = (errorCode) => {
    const genericError = "Invalid number";
    const { validationError } = intlTelInput.utils;
    const errorMap = {
      [validationError.INVALID_COUNTRY_CODE]: "Invalid country code",
      [validationError.TOO_SHORT]: "Too short",
      [validationError.TOO_LONG]: "Too long",
      [validationError.INVALID_LENGTH]: genericError,
    };
    return errorMap[errorCode] || genericError;
  };

  let isValid = $state(null);
  let number = $state(null);
  let errorCode = $state(null);
  let notice = $state(null);

  const handleSubmit = () => {
    if (isValid) {
      notice = `Valid number: ${number}`;
    } else {
      const errorMessage = getErrorMessage(errorCode);
      notice = `Error: ${errorMessage}`;
    }
  };
</script>

<form>
  <IntlTelInput
    onChangeNumber={(n) => number = n}
    onChangeValidity={(v) => isValid = v}
    onChangeErrorCode={(e) => errorCode = e}
    initialCountry="us"
  />
  <button class="button" type="button" onclick={handleSubmit}>Validate</button>
  {#if notice}
    <div class="notice">{notice}</div>
  {/if}
</form>
