// packages/svelte/src/IntlTelInput.svelte
<script module lang="ts">
  import intlTelInput, { type Iti } from "intl-tel-input";
  export { intlTelInput };
</script>

<script lang="ts">
  // Resolves to IntlTelInput.svelte.d.ts (the type declaration file for this component).
  import type { Props } from "./IntlTelInput.svelte";
  import type { SomeOptions, ValidationError } from "intl-tel-input";
  import { onMount, onDestroy } from "svelte";

  // Props
  let {
    disabled = false,
    readonly = false,
    inputProps = {},
    usePreciseValidation = false,
    initialValue = "",
    value = undefined,
    onChangeNumber,
    onChangeCountry,
    onChangeValidity,
    onChangeErrorCode,
    onOpenCountrySelector,
    onCloseCountrySelector,
    onStrictReject,
    ...initOptions
  } = $props() as Props;

  type StrictRejectDetail = {
    source: "key" | "paste";
    rejectedInput: string;
    reason: "invalid" | "max-length";
  };

  // State
  let inputElement: HTMLInputElement | undefined = $state();
  let instance: Iti | undefined = $state();
  // Classes the library adds directly to the input (e.g. iti__tel-input)
  let libraryInputClasses = $state("");
  let lastEmittedNumber: string | undefined = $state();
  let lastEmittedCountry: string | undefined = $state();
  let lastEmittedValidity: boolean | undefined = $state();
  let lastEmittedErrorCode: ValidationError | null | undefined = $state();
  let hasInitialized = $state(false);
  // if an input event fires before utils has loaded, we defer the update until the promise resolves
  let pendingUpdate = false;

  // Validation helper
  const isValid = (): boolean | null => {
    if (!instance) return null;
    return usePreciseValidation
      ? instance.isValidNumberPrecise()
      : instance.isValidNumber();
  };

  // Update handlers
  const updateValidity = () => {
    if (!instance) return;
    // if utils has not loaded yet, isValidNumber/getValidationError will throw. defer until the promise resolves.
    if (!intlTelInput.utils) {
      pendingUpdate = true;
      return;
    }
    const isCurrentlyValid = isValid();
    if (isCurrentlyValid === null) return;

    const valid = !!isCurrentlyValid;
    const errorCode = valid ? null : instance.getValidationError();

    if (valid !== lastEmittedValidity) {
      lastEmittedValidity = valid;
      onChangeValidity?.(valid);
    }

    if (errorCode !== lastEmittedErrorCode) {
      lastEmittedErrorCode = errorCode;
      onChangeErrorCode?.(errorCode);
    }
  };

  const updateValue = () => {
    if (!instance?.isActive()) {
      return;
    }
    // if utils has not loaded yet, getNumber will throw. defer until the promise resolves.
    if (!intlTelInput.utils) {
      pendingUpdate = true;
      return;
    }
    const number = instance.getNumber() ?? "";
    if (number !== lastEmittedNumber) {
      lastEmittedNumber = number;
      onChangeNumber?.(number);
    }
    updateValidity();
  };

  const updateCountry = () => {
    if (!instance?.isActive()) {
      return;
    }
    const country = instance.getSelectedCountry()?.iso2 ?? "";
    if (country !== lastEmittedCountry) {
      lastEmittedCountry = country;
      onChangeCountry?.(country);
    }
    updateValue();
  };

  const handleOpenCountrySelector = (): void => onOpenCountrySelector?.();
  const handleCloseCountrySelector = (): void => onCloseCountrySelector?.();
  const handleStrictReject = (e: Event): void => {
    const { source, rejectedInput, reason } = (e as CustomEvent<StrictRejectDetail>).detail;
    onStrictReject?.(source, rejectedInput, reason);
  };

  // Lifecycle
  onMount(() => {
    if (inputElement) {
      //* Record only the classes the library itself adds during init (iti__tel-input, plus any
      //* classNames.input), by diffing the class list across the call. Capturing the whole className
      //* would also scoop up any inputProps.class already rendered, which would then be re-applied on
      //* every subsequent render - so a changed inputProps.class would leave the old value behind,
      //* and an unchanged one would be duplicated.
      const classesBeforeInit = new Set(inputElement.classList);
      instance = intlTelInput(inputElement, initOptions as SomeOptions);
      libraryInputClasses = Array.from(inputElement.classList)
        .filter((className) => !classesBeforeInit.has(className))
        .join(" ");
      if (disabled) instance.setDisabled(disabled);
      if (readonly) instance.setReadonly(readonly);

      inputElement.addEventListener("open:countryselector", handleOpenCountrySelector);
      inputElement.addEventListener("close:countryselector", handleCloseCountrySelector);
      inputElement.addEventListener("strict:reject", handleStrictReject);

      lastEmittedCountry = instance.getSelectedCountry()?.iso2 ?? "";
      hasInitialized = true;

      // wait for utils to load before calling methods that require it (getNumber, setNumber, isValidNumber, etc.)
      instance.promise.then(() => {
        if (!instance?.isActive()) return;
        if (initialValue) instance.setNumber(initialValue);
        // if an input event fired during the utils-loading gap, replay it now so the skipped emissions fire.
        // otherwise seed silently so we don't fire change callbacks on initial mount.
        if (pendingUpdate) {
          pendingUpdate = false;
          updateCountry();
        } else {
          lastEmittedNumber = instance.getNumber() ?? "";
          const initialValid = isValid();
          if (initialValid !== null) {
            lastEmittedValidity = !!initialValid;
            lastEmittedErrorCode = initialValid ? null : instance.getValidationError();
          }
        }
      });
    }
  });

  onDestroy(() => {
    if (inputElement) {
      inputElement.removeEventListener("open:countryselector", handleOpenCountrySelector);
      inputElement.removeEventListener("close:countryselector", handleCloseCountrySelector);
      inputElement.removeEventListener("strict:reject", handleStrictReject);
    }
    instance?.destroy();
  });

  // Watch disabled prop changes (only after initialization)
  $effect(() => {
    if (hasInitialized && instance) {
      instance.setDisabled(disabled);
    }
  });

  // Watch readonly prop changes (only after initialization)
  $effect(() => {
    if (hasInitialized && instance) {
      instance.setReadonly(readonly);
    }
  });

  // Watch value prop changes (only after initialization).
  // If value is undefined, the component is uncontrolled — do not touch the input
  // (otherwise we would clobber any initialValue with an empty string on mount).
  $effect(() => {
    if (!hasInitialized || !instance || value === undefined) {
      return;
    }
    const next = value ?? "";
    // wait for utils to load before calling methods that require it
    instance.promise.then(() => {
      if (!instance?.isActive()) return;
      const currentCanonical = instance.getNumber() ?? "";
      const isFocused = document.activeElement === inputElement;
      if (isFocused || currentCanonical === next) {
        return;
      }
      instance.setNumber(next);
      updateValidity();
    });
  });

  // Expose instance and input for parent access
  export function getInstance(): Iti | undefined {
    return instance;
  }
  export function getInput(): HTMLInputElement | undefined {
    return inputElement;
  }

  const warnInputProp = (prop: string): void => {
    console.warn(`intl-tel-input: ignoring inputProps.${prop} - see docs for more info.`);
  };

  const ignoredInputProps = new Set(["type", "value", "disabled", "readonly", "oninput"]);

  const sanitizeInputProps = (props: Record<string, unknown>) => {
    const rest: Record<string, unknown> = {};
    for (const [key, val] of Object.entries(props)) {
      if (ignoredInputProps.has(key)) {
        warnInputProp(key);
      } else if (key === "class") {
        // Re-apply the library's own classes alongside the consumer's, as Svelte owns the attribute
        // (filter out empties so we never emit a stray "undefined" class or leading whitespace)
        rest[key] = [libraryInputClasses, val].filter(Boolean).join(" ");
      } else {
        rest[key] = val;
      }
    }
    return rest;
  };
</script>

<!-- inputProps must come first, so cannot override the other required props -->
<input
  {...sanitizeInputProps(inputProps)}
  bind:this={inputElement}
  type="tel"
  oninput={updateCountry}
/>

// packages/react/src/IntlTelInput.tsx
import intlTelInput, { Iti } from "intl-tel-input";
import type { SomeOptions, ValidationError } from "intl-tel-input";
import React, {
  useRef,
  useEffect,
  forwardRef,
  useImperativeHandle,
  useCallback,
} from "react";

// make this available as a named export, so react users can access globals like intlTelInput.utils
export { intlTelInput };

const warnInputProp = (prop: string): void => {
  console.warn(`intl-tel-input: ignoring inputProps.${prop} - see docs for more info.`);
};

type InputProps = Omit<React.ComponentPropsWithoutRef<"input">, "onInput">;

const noop = () => {};

export type StrictRejectSource = "key" | "paste";
export type StrictRejectReason = "invalid" | "max-length";
type StrictRejectDetail = {
  source: StrictRejectSource;
  rejectedInput: string;
  reason: StrictRejectReason;
};

type ItiProps = SomeOptions & {
  onChangeNumber?: (number: string) => void;
  onChangeCountry?: (iso2: string) => void;
  onChangeValidity?: (isValid: boolean) => void;
  onChangeErrorCode?: (errorCode: ValidationError | null) => void;
  onOpenCountrySelector?: () => void;
  onCloseCountrySelector?: () => void;
  onStrictReject?: (source: StrictRejectSource, rejectedInput: string, reason: StrictRejectReason) => void;
  usePreciseValidation?: boolean;
  inputProps?: InputProps;
  disabled?: boolean | undefined;
  readOnly?: boolean | undefined;
  value?: string | null;
};

export type IntlTelInputRef = {
  getInstance: () => Iti | null;
  getInput: () => HTMLInputElement | null;
};

// Note: React v19 supports ref forwarding with function components, but we still need to use forwardRef to support React v18
const IntlTelInput = forwardRef(function IntlTelInput(
  {
    onChangeNumber = noop,
    onChangeCountry = noop,
    onChangeValidity = noop,
    onChangeErrorCode = noop,
    onOpenCountrySelector,
    onCloseCountrySelector,
    onStrictReject,
    usePreciseValidation = false,
    inputProps = {},
    disabled = undefined,
    readOnly = undefined,
    value = undefined,
    ...initOptions
  }: ItiProps,
  ref: React.ForwardedRef<IntlTelInputRef>,
) {
  const inputRef = useRef<HTMLInputElement | null>(null);
  const itiRef = useRef<Iti | null>(null);
  // Classes the library adds directly to the input (e.g. iti__tel-input)
  const libraryInputClassesRef = useRef<string>("");
  const lastEmittedNumberRef = useRef<string | undefined>(undefined);
  const lastEmittedCountryRef = useRef<string | undefined>(undefined);
  const lastEmittedValidityRef = useRef<boolean | undefined>(undefined);
  const lastEmittedErrorCodeRef = useRef<ValidationError | null | undefined>(undefined);
  // if an input event fires before utils has loaded, we defer the update until the promise resolves
  const pendingUpdateRef = useRef<boolean>(false);

  // keep latest pass-through event handlers in refs so listeners registered once always see fresh callbacks
  const onOpenCountrySelectorRef = useRef(onOpenCountrySelector);
  const onCloseCountrySelectorRef = useRef(onCloseCountrySelector);
  const onStrictRejectRef = useRef(onStrictReject);
  onOpenCountrySelectorRef.current = onOpenCountrySelector;
  onCloseCountrySelectorRef.current = onCloseCountrySelector;
  onStrictRejectRef.current = onStrictReject;

  // expose the instance and input ref to the parent component
  useImperativeHandle(ref, () => ({
    getInstance: () => itiRef.current,
    getInput: () => inputRef.current,
  }));

  const seedInitialState = useCallback((): void => {
    if (!itiRef.current?.isActive()) {
      return;
    }
    lastEmittedNumberRef.current = itiRef.current.getNumber() ?? "";
    lastEmittedCountryRef.current = itiRef.current.getSelectedCountry()?.iso2 ?? "";
    const isValid = (usePreciseValidation
      ? itiRef.current.isValidNumberPrecise()
      : itiRef.current.isValidNumber()) ?? false;
    lastEmittedValidityRef.current = isValid;
    lastEmittedErrorCodeRef.current = isValid ? null : itiRef.current.getValidationError();
  }, [usePreciseValidation]);

  const update = useCallback((): void => {
    // if the instance is not valid (e.g. has been destroyed/unmounted), do not attempt to call any methods on it
    if (!itiRef.current?.isActive()) {
      return;
    }
    // if utils has not loaded yet, getNumber/isValidNumber/etc. will throw. defer until the promise resolves.
    if (!intlTelInput.utils) {
      pendingUpdateRef.current = true;
      return;
    }
    const num = itiRef.current.getNumber() ?? "";
    const countryIso = itiRef.current.getSelectedCountry()?.iso2 ?? "";
    // note: this number will be in standard E164 format, but any container component can use
    // intlTelInput.utils.formatNumber() to convert this to another format
    // as well as intlTelInput.utils.getNumberType() etc. if need be
    if (num !== lastEmittedNumberRef.current) {
      lastEmittedNumberRef.current = num;
      onChangeNumber(num);
    }
    if (countryIso !== lastEmittedCountryRef.current) {
      lastEmittedCountryRef.current = countryIso;
      onChangeCountry(countryIso);
    }

    const isValid = (usePreciseValidation
      ? itiRef.current.isValidNumberPrecise()
      : itiRef.current.isValidNumber()) ?? false;
    const errorCode = isValid ? null : itiRef.current.getValidationError();

    if (isValid !== lastEmittedValidityRef.current) {
      lastEmittedValidityRef.current = isValid;
      onChangeValidity(isValid);
    }
    if (errorCode !== lastEmittedErrorCodeRef.current) {
      lastEmittedErrorCodeRef.current = errorCode;
      onChangeErrorCode(errorCode);
    }
  }, [
    onChangeCountry,
    onChangeErrorCode,
    onChangeNumber,
    onChangeValidity,
    usePreciseValidation,
  ]);

  useEffect(() => {
    const inputEl = inputRef.current;
    if (!inputEl) {
      return undefined;
    }
    //* Record only the classes the library itself adds during init (iti__tel-input, plus any
    //* classNames.input), by diffing the class list across the call. Capturing the whole className
    //* would also scoop up any inputProps.className React has already rendered, which would then be
    //* re-applied on every subsequent render - so a changed inputProps.className would leave the old
    //* value behind, and an unchanged one would be duplicated.
    const classesBeforeInit = new Set(inputEl.classList);
    itiRef.current = intlTelInput(inputEl, initOptions as SomeOptions);
    libraryInputClassesRef.current = Array.from(inputEl.classList)
      .filter((className) => !classesBeforeInit.has(className))
      .join(" ");

    const handleOpen = (): void => onOpenCountrySelectorRef.current?.();
    const handleClose = (): void => onCloseCountrySelectorRef.current?.();
    const handleStrictReject = (e: Event): void => {
      const { source, rejectedInput, reason } = (e as CustomEvent<StrictRejectDetail>).detail;
      onStrictRejectRef.current?.(source, rejectedInput, reason);
    };
    inputEl.addEventListener("open:countryselector", handleOpen);
    inputEl.addEventListener("close:countryselector", handleClose);
    inputEl.addEventListener("strict:reject", handleStrictReject);

    return (): void => {
      inputEl.removeEventListener("open:countryselector", handleOpen);
      inputEl.removeEventListener("close:countryselector", handleClose);
      inputEl.removeEventListener("strict:reject", handleStrictReject);
      itiRef.current?.destroy();
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    itiRef.current?.promise.then(() => {
      if (!itiRef.current?.isActive()) {
        return;
      }
      // if an input event fired during the utils-loading gap, replay it now so the skipped emissions fire.
      // otherwise seed the refs with current state so we don't fire change callbacks on initial mount.
      if (pendingUpdateRef.current) {
        pendingUpdateRef.current = false;
        update();
      } else {
        seedInitialState();
      }
    });
  }, [seedInitialState, update]);

  useEffect(() => {
    if (itiRef.current && disabled !== undefined) {
      itiRef.current.setDisabled(disabled);
    }
  }, [disabled]);

  useEffect(() => {
    if (itiRef.current && readOnly !== undefined) {
      itiRef.current.setReadonly(readOnly);
    }
  }, [readOnly]);

  useEffect(() => {
    // if value is undefined, the component is uncontrolled - do not touch the input
    if (!itiRef.current || value === undefined) {
      return;
    }
    // wait for utils to load before trying to access iti methods that use it, e.g. getNumber, setNumber, etc.
    itiRef.current.promise.then(() => {
      if (!itiRef.current?.isActive()) {
        return;
      }
      const next = value ?? "";
      const currentCanonical = itiRef.current.getNumber() ?? "";
      const isFocused = document.activeElement === inputRef.current;
      if (isFocused || currentCanonical === next) {
        return;
      }
      itiRef.current.setNumber(next);
      update();
    });
  }, [value, update]);

  // ignore keys that would break functionality
  const ignoredInputProps = new Set(["type", "ref", "value", "disabled", "readOnly", "onInput"]);

  const sanitizedInputProps: Record<string, unknown> = {};
  for (const [key, val] of Object.entries(inputProps)) {
    if (ignoredInputProps.has(key)) {
      warnInputProp(key);
    } else if (key === "className") {
      // Re-apply the library's own classes alongside the consumer's, as React owns the attribute
      // (filter out empties so we never emit a stray "undefined" class or leading whitespace)
      sanitizedInputProps[key] = [libraryInputClassesRef.current, val]
        .filter(Boolean)
        .join(" ");
    } else {
      sanitizedInputProps[key] = val;
    }
  }

  // The iti library reparents the input into its own `.iti` wrapper at init time.
  // If the <input> is the component's direct output, React's fiber tree (which still
  // thinks the input is a direct child of its host container) and the real DOM diverge,
  // and React 19's commit phase throws NotFoundError when it tries to call
  // parent.removeChild(input) on the wrong parent. Wrapping the input in a stable
  // React-owned element means React only ever needs to mutate *that* element as a
  // child of its container - iti's reparenting happens entirely inside it.
  // `display: contents` keeps the wrapper out of the layout tree so iti's own
  // styling (inline-block on `.iti`) is preserved.
  return (
    <span style={{ display: "contents" }}>
      <input
        {...(sanitizedInputProps as InputProps)}
        type="tel"
        ref={inputRef}
        onInput={update}
      />
    </span>
  );
});

export default IntlTelInput;
