// site/src/examples/svelte-component/display-existing-number/display_code.svelte
<script>
  import IntlTelInput from "intl-tel-input/svelte";
  import "intl-tel-input/styles";
</script>

<label for="phone">Phone number</label>
<IntlTelInput
  separateDialCode={true}
  initialValue="+447733312345"
  loadUtils={() => import("intl-tel-input/utils")}
  inputProps={{ id: "phone" }}
/>

// site/src/examples/vue-component/display-existing-number/display_code.vue
<script setup>
  import IntlTelInput from "@intl-tel-input/vue";
  import "intl-tel-input/styles";
</script>

<template>
  <label for="phone">Phone number</label>
  <IntlTelInput
    initial-value="+447733312345"
    :load-utils="() => import('intl-tel-input/utils')"
    :input-props="{ id: 'phone' }"
  />
</template>
