// site/src/examples/svelte-component/display-existing-number/display_code.svelte
<script>
  import IntlTelInput from "intl-tel-input/svelte";
  import "intl-tel-input/styles";
</script>

<label for="phone">Phone number</label>
<IntlTelInput
  separateDialCode={true}
  initialValue="+447733312345"
  loadUtils={() => import("intl-tel-input/utils")}
  inputProps={{ id: "phone" }}
/>

// site/src/examples/react-component/display-existing-number/display_code.js
import React from "react";
import IntlTelInput from "intl-tel-input/react";
import "intl-tel-input/styles";

const App = () => (
  <>
    <label htmlFor="phone">Phone number</label>
    <IntlTelInput
      separateDialCode
      loadUtils={() => import("intl-tel-input/utils")}
      inputProps={{
        id: "phone",
        defaultValue: "+447733312345",
      }}
    />
  </>
);
export default App;
